# Generated by Django 4.0.6 on 2022-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages_words',
            name='translate',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='languages_words',
            name='word',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
