# Generated by Django 4.0.6 on 2022-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_grossvolume_alter_item_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
