# Generated by Django 4.0.6 on 2022-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='EnergySource_generator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
