# Generated by Django 4.1.4 on 2023-01-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_energysource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='CoolWaterProductionCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='CoolantPackNominalCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
