# Generated by Django 4.0.6 on 2022-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_powerorfuelconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='FreezerNetCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='IceMakingCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='NetVaccineStorageCapacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
