# Generated by Django 4.0.6 on 2022-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_freezernetcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isDel',
            field=models.BooleanField(default=False),
        ),
    ]
