# Generated by Django 4.1.4 on 2023-01-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_coolwaterproductioncapacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='OtherFieldsItem1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
