# Generated by Django 4.0.6 on 2022-08-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, choices=[('admin', 'Admin'), ('index', 'Index'), ('Facility_info', 'Facility Info'), ('Facility_type', 'Facility Type'), ('Item_type', 'Item Type'), ('User_type', 'User Type'), ('Item_info', 'Item Info'), ('User_info', 'User Info'), ('admin_guide', 'Admin Guide')], max_length=20, null=True)),
                ('lang', models.CharField(blank=True, choices=[('arabic', 'Arabic'), ('english', 'English'), ('persian', 'Persian'), ('french', 'French'), ('russian', 'Russian')], max_length=20, null=True)),
                ('abr', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
