# Generated by Django 4.0.6 on 2022-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'En'), ('fr', 'Fr'), ('ar', 'Ar'), ('ot', 'Ot'), ('es', 'Es'), ('ru', 'Ru'), ('ch', 'Ch'), ('uk', 'Uk')], max_length=20, null=True),
        ),
    ]
