# Generated by Django 4.1.4 on 2022-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_help_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'En'), ('fr', 'Fr'), ('ar', 'Ar'), ('ot', 'Ot'), ('es', 'Es'), ('ru', 'Ru'), ('uk', 'Uk'), ('vi', 'Vi')], max_length=20, null=True),
        ),
    ]
