# Generated by Django 4.0.6 on 2022-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_help_abr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='abr',
            field=models.FileField(blank=True, null=True, upload_to='help'),
        ),
        migrations.AlterField(
            model_name='help',
            name='lang',
            field=models.CharField(blank=True, choices=[('English', 'En'), ('Français', 'Fr'), ('العربية', 'Ar'), ('فارسی', 'Fa'), ('Español', 'Es'), ('Русский', 'Ru')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='page',
            field=models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('Facilities', 'Facilities'), ('Human Resources', 'Hr'), ('User', 'User'), ('Message', 'Message'), ('Reports', 'Reports'), ('Settings', 'Settings'), ('About-IGA', 'About Iga')], max_length=20, null=True),
        ),
    ]
