# Generated by Django 4.0.6 on 2022-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_alter_help_abr_alter_help_lang_alter_help_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'En'), ('fr', 'Fr'), ('ar', 'Ar'), ('fa', 'Fa'), ('es', 'Es'), ('ru', 'Ru')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='page',
            field=models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('facilities', 'Facilities'), ('hr', 'Hr'), ('user', 'User'), ('message', 'Message'), ('reports', 'Reports'), ('settings', 'Settings'), ('about-iga', 'About Iga')], max_length=20, null=True),
        ),
    ]
