# Generated by Django 4.0.6 on 2022-09-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('populationnumber', models.IntegerField(blank=True, db_column='populationNumber', null=True)),
                ('childrennumber', models.IntegerField(blank=True, db_column='childrenNumber', null=True)),
                ('loverlevelfac', models.IntegerField(blank=True, db_column='loverLevelFac', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(blank=True, db_column='province', max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=12, null=True)),
                ('national_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('gpsCordinate', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('land_phone', models.BooleanField(default=False)),
                ('haveinternet', models.BooleanField(blank=True, db_column='haveInternet', null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_functioning', models.BooleanField(default=True)),
                ('climate', models.CharField(blank=True, max_length=50, null=True)),
                ('ownership', models.CharField(blank=True, max_length=50, null=True)),
                ('roadtype', models.CharField(blank=True, db_column='roadType', max_length=50, null=True)),
                ('distancefromparent', models.IntegerField(blank=True, db_column='distanceFromParent', null=True)),
                ('timetoparent', models.CharField(blank=True, db_column='timeToParent', max_length=50, null=True)),
                ('days_open', models.IntegerField(blank=True, db_column='daysOpen', null=True)),
                ('working_from', models.CharField(blank=True, db_column='workingFrom', max_length=50, null=True)),
                ('working_to', models.CharField(blank=True, db_column='workingTo', max_length=50, null=True)),
                ('recieve_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('haveimmservice', models.BooleanField(blank=True, db_column='HaveImmService', null=True)),
                ('typeimmservice', models.IntegerField(blank=True, db_column='TypeImmService', null=True)),
                ('numimmperweek', models.IntegerField(blank=True, db_column='NumImmperWeek', null=True)),
                ('havecovid19service', models.BooleanField(blank=True, db_column='HaveCovid19Service', null=True)),
                ('coverageX1', models.IntegerField(blank=True, db_column='CoverageX1', null=True)),
                ('coverageX2', models.IntegerField(blank=True, db_column='CoverageX2', null=True)),
                ('coverageX3', models.IntegerField(blank=True, db_column='CoverageX3', null=True)),
                ('coverageX4', models.IntegerField(blank=True, db_column='CoverageX4', null=True)),
                ('individualsX1', models.IntegerField(blank=True, db_column='IndividualsX1', null=True)),
                ('individualsX2', models.IntegerField(blank=True, db_column='IndividualsX2', null=True)),
                ('individualsX3', models.IntegerField(blank=True, db_column='IndividualsX3', null=True)),
                ('individualsX4', models.IntegerField(blank=True, db_column='IndividualsX4', null=True)),
                ('number_icepack', models.IntegerField(blank=True, db_column='NumberIcepack', null=True)),
                ('other_service', models.BooleanField(blank=True, db_column='OtherService', null=True)),
                ('other_services', models.CharField(blank=True, max_length=50, null=True)),
                ('is_suitable', models.BooleanField(blank=True, db_column='IsSuitable', null=True)),
                ('is_suitable_reason', models.CharField(blank=True, db_column='IsSuitableReason', max_length=50, null=True)),
                ('havegen', models.BooleanField(blank=True, db_column='HaveGen', null=True)),
                ('powersource', models.CharField(blank=True, db_column='PowerSource', max_length=50, null=True)),
                ('maintance', models.CharField(blank=True, db_column='Maintance', max_length=50, null=True)),
                ('vac_num', models.IntegerField(blank=True, db_column='VacNum', null=True)),
                ('total_staff', models.IntegerField(blank=True, db_column='TotalStaff', null=True)),
                ('prof_staff', models.IntegerField(blank=True, db_column='ProfStaff', null=True)),
                ('nurses', models.IntegerField(blank=True, db_column='Nurses', null=True)),
                ('drivers', models.IntegerField(blank=True, db_column='Drivers', null=True)),
                ('other_staff', models.IntegerField(blank=True, db_column='OtherStaff', null=True)),
                ('other1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other3', models.BooleanField(blank=True, null=True)),
                ('other4', models.BooleanField(blank=True, null=True)),
                ('other5', models.CharField(blank=True, max_length=100, null=True)),
                ('other6', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('completerstaffsign', models.CharField(blank=True, db_column='completerStaffSign', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('completerstaffname', models.ForeignKey(blank=True, db_column='completerStaff', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.countryconfig')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.levelconfig')),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facility')),
            ],
            options={
                'db_table': 'Facility',
            },
        ),
    ]
