# Generated by Django 4.0.6 on 2022-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='other_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
