# Generated by Django 4.0.6 on 2022-08-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='code',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='countvacc1',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='countvacc2',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='coverage1',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='endwork',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='functionstatus',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='havegenerator',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='name',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='numdriverstaff',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='numprofstaff',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='numvaccstaff',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='receivingvaccmode',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='staffnumber',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='startwork',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='transportmode',
        ),
        migrations.AddField(
            model_name='facility',
            name='coverageX1',
            field=models.IntegerField(blank=True, db_column='CoverageX1', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='coverageX2',
            field=models.IntegerField(blank=True, db_column='CoverageX2', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='coverageX3',
            field=models.IntegerField(blank=True, db_column='CoverageX3', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='coverageX4',
            field=models.IntegerField(blank=True, db_column='CoverageX4', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='days_open',
            field=models.IntegerField(blank=True, db_column='daysOpen', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='drivers',
            field=models.IntegerField(blank=True, db_column='Drivers', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='havegen',
            field=models.BooleanField(blank=True, db_column='HaveGen', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='individualsX1',
            field=models.IntegerField(blank=True, db_column='IndividualsX1', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='individualsX2',
            field=models.IntegerField(blank=True, db_column='IndividualsX2', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='individualsX3',
            field=models.IntegerField(blank=True, db_column='IndividualsX3', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='individualsX4',
            field=models.IntegerField(blank=True, db_column='IndividualsX4', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_functioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_suitable',
            field=models.BooleanField(blank=True, db_column='IsSuitable', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_suitable_reason',
            field=models.CharField(blank=True, db_column='IsSuitableReason', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='land_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='loverlevelfac',
            field=models.IntegerField(blank=True, db_column='loverLevelFac', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='maintance',
            field=models.CharField(blank=True, db_column='Maintance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='number_icepack',
            field=models.IntegerField(blank=True, db_column='NumberIcepack', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nurses',
            field=models.IntegerField(blank=True, db_column='Nurses', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='other_service',
            field=models.BooleanField(blank=True, db_column='OtherService', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='other_staff',
            field=models.IntegerField(blank=True, db_column='OtherStaff', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='prof_staff',
            field=models.IntegerField(blank=True, db_column='ProfStaff', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='recieve_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='total_staff',
            field=models.IntegerField(blank=True, db_column='TotalStaff', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='working_from',
            field=models.TimeField(blank=True, db_column='workingFrom', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='working_to',
            field=models.TimeField(blank=True, db_column='workingTo', null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='climate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='powersource',
            field=models.CharField(blank=True, db_column='PowerSource', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
