# Generated by Django 4.0.6 on 2022-08-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_remove_facility_barcode_remove_facility_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
