# Generated by Django 4.0.6 on 2022-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_other_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
