# Generated by Django 4.0.6 on 2022-09-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
    ]
