# Generated by Django 4.0.6 on 2022-08-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
