# Generated by Django 4.0.6 on 2022-09-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('facilities', '0004_alter_facility_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.countryconfig'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.levelconfig'),
        ),
    ]
