# Generated by Django 4.0.6 on 2022-08-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='other_services',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='vac_num',
            field=models.IntegerField(blank=True, db_column='VacNum', null=True),
        ),
    ]
