# Generated by Django 4.0.6 on 2022-09-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_facility_country_alter_facility_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='distancefromparent',
            field=models.FloatField(blank=True, db_column='distanceFromParent', null=True),
        ),
    ]
