# Generated by Django 4.0.6 on 2022-08-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facility_other_services_facility_vac_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='working_from',
            field=models.CharField(blank=True, db_column='workingFrom', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='working_to',
            field=models.CharField(blank=True, db_column='workingTo', max_length=50, null=True),
        ),
    ]
