# Generated by Django 4.0.6 on 2022-09-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_levelconfig_maxpop_alter_levelconfig_minpop'),
        ('facilities', '0006_alter_facility_working_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.countryconfig'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.levelconfig'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facility'),
        ),
    ]
