# Generated by Django 4.0.6 on 2022-09-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_facility_country_alter_facility_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
