# Generated by Django 4.0.6 on 2022-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_alter_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_deleted',
            field=models.BooleanField(blank=True, db_column='isDeleted', null=True),
        ),
    ]
