# Generated by Django 4.0.6 on 2022-09-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_facility_delete_reason_facility_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='is_deleted',
            field=models.BooleanField(blank=True, db_column='isDeleted', default=False, null=True),
        ),
    ]
