# Generated by Django 4.0.6 on 2022-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_alter_facility_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='is_deleted',
            field=models.BooleanField(db_column='isDeleted', default=False),
        ),
    ]
