# Generated by Django 4.0.6 on 2022-08-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pqs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
                ('make', models.CharField(blank=True, db_column='Make', max_length=100, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=100, null=True)),
                ('pqscode', models.CharField(blank=True, db_column='PQScode', max_length=50, null=True)),
                ('refrigerant', models.CharField(blank=True, db_column='Refrigerant', max_length=50, null=True)),
                ('tempzone', models.CharField(blank=True, db_column='Tempzone', max_length=50, null=True)),
                ('refrigeratorcapacity', models.FloatField(blank=True, db_column='RefrigeratorCapacity', null=True)),
                ('freezercapacity', models.FloatField(blank=True, db_column='FreezerCapacity', null=True)),
                ('kg_24_hrs', models.FloatField(blank=True, null=True)),
                ('waterpackstoragecapacity', models.FloatField(blank=True, db_column='WaterpackStorageCapacity', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('h', models.FloatField(blank=True, db_column='H', null=True)),
                ('w', models.FloatField(blank=True, db_column='W', null=True)),
                ('l', models.FloatField(blank=True, db_column='L', null=True)),
                ('volume', models.FloatField(blank=True, db_column='Volume', null=True)),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pqs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqsnumber', models.CharField(db_column='PQSNumber', max_length=100)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=100, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=100, null=True)),
                ('vaccinenetstoragecapacity', models.FloatField(blank=True, db_column='VaccineNetStorageCapacity', null=True)),
                ('coolantpacknominalcapacity', models.FloatField(blank=True, db_column='CoolantPackNominalCapacity', null=True)),
                ('numbercoolantpacks', models.IntegerField(blank=True, db_column='NumberCoolantPacks', null=True)),
                ('externalvolume', models.FloatField(blank=True, db_column='ExternalVolume', null=True)),
            ],
        ),
    ]
