# Generated by Django 4.0.6 on 2022-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQS', '0002_remove_pqs3_price_remove_pqs3_tempzone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqs3',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pqs4',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
