# Generated by Django 4.0.6 on 2022-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position_level', models.CharField(blank=True, max_length=100, null=True)),
                ('genders', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('educatioin_level', models.CharField(blank=True, max_length=100, null=True)),
                ('years_in_service', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_in_position', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
