# Generated by Django 4.0.6 on 2022-08-17 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_code'),
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
    ]
