# Generated by Django 4.0.6 on 2022-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_alter_hr_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
