# Generated by Django 4.0.6 on 2022-08-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_hr_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='gender',
            new_name='genders',
        ),
    ]
