# Generated by Django 4.0.6 on 2022-12-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
