# Generated by Django 4.0.6 on 2022-08-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
