# Generated by Django 4.0.6 on 2022-09-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('havePQS', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('itemclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemclass')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('itemclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemclass')),
            ],
        ),
        migrations.CreateModel(
            name='Itemtypelevel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('itemtypeid', models.ForeignKey(blank=True, db_column='itemTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.levelconfig')),
            ],
        ),
    ]
