# Generated by Django 4.0.6 on 2022-08-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
