# Generated by Django 4.0.6 on 2022-08-13 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_levelconfig_number'),
        ('items', '0003_itemtype_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemtypelevel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemtypeid', models.ForeignKey(blank=True, db_column='itemTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.levelconfig')),
            ],
        ),
    ]
