# Generated by Django 4.0.6 on 2022-08-13 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_levelconfig_number'),
        ('items', '0004_itemtypelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtypelevel',
            name='itemtypeid',
            field=models.ForeignKey(blank=True, db_column='itemTypeID', on_delete=django.db.models.deletion.CASCADE, to='items.itemtype'),
        ),
        migrations.AlterField(
            model_name='itemtypelevel',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='settings.levelconfig'),
        ),
    ]
