# Generated by Django 4.0.6 on 2022-08-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_itemtypelevel_itemtypeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtypelevel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
