# Generated by Django 4.0.6 on 2022-08-15 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemtypelevel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('itemclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemclass')),
            ],
        ),
    ]
