# Generated by Django 4.0.6 on 2022-08-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelconfig',
            name='number',
        ),
    ]
