# Generated by Django 4.0.6 on 2022-09-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_levelconfig_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelconfig',
            name='maxpop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='minpop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
