# Generated by Django 4.0.6 on 2022-09-02 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0006_alter_facility_working_from_and_more'),
        ('settings', '0002_remove_levelconfig_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='gapSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('condition', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('req_capacity', models.FloatField(default=0)),
                ('available', models.FloatField(default=0)),
                ('func_cap', models.FloatField(default=0)),
                ('exces', models.FloatField(default=0)),
                ('planned', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facility_gap', to='facilities.facility')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level', to='settings.levelconfig')),
                ('parent_fac', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_fac', to='facilities.facility')),
            ],
        ),
    ]
