# Generated by Django 4.0.6 on 2022-09-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapsave',
            name='general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gapsave',
            name='under_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='condition',
            field=models.IntegerField(),
        ),
    ]
