# Generated by Django 4.0.6 on 2022-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapsave',
            name='general',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='under_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
