# Generated by Django 4.0.6 on 2022-09-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('facilities', '0005_alter_facility_country_alter_facility_level'),
        ('reports', '0002_alter_gapsave_general_alter_gapsave_under_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapsave',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_gap', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='settings.levelconfig'),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='parent_fac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_fac', to='facilities.facility'),
        ),
    ]
