# Generated by Django 4.0.6 on 2022-09-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_facility_working_from_and_more'),
        ('settings', '0002_remove_levelconfig_number'),
        ('reports', '0002_gapsave_general_gapsave_under_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapsave',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='facility_gap', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level', to='settings.levelconfig'),
        ),
        migrations.AlterField(
            model_name='gapsave',
            name='parent_fac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_fac', to='facilities.facility'),
        ),
    ]
