# Generated by Django 4.0.6 on 2022-09-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_gapsave_code_alter_gapsave_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapsave',
            name='calculate_for',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
