# Generated by Django 4.0.6 on 2022-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_plannedgap'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedgap',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
