# Generated by Django 4.0.6 on 2022-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_plannedgap_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedgap',
            name='count',
        ),
        migrations.AddField(
            model_name='plannedgap',
            name='provided',
            field=models.BooleanField(default=False),
        ),
    ]
