# Generated by Django 4.0.6 on 2022-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_plannedgap_count_plannedgap_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedgap',
            name='asiign',
            field=models.BooleanField(default=False),
        ),
    ]
