# Generated by Django 4.0.6 on 2022-09-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintanance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('enable', models.BooleanField(blank=True, default=True, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('requires', models.BooleanField(blank=True, default=True, null=True)),
                ('freq_in_loc', models.IntegerField(blank=True, null=True)),
                ('item_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemclass')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='maintancegp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('enable', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemclass')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='toDoMaintance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('maintanance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintanance')),
                ('maintanncegp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintancegp')),
            ],
        ),
        migrations.CreateModel(
            name='doneMaintance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('maintanance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintanance')),
                ('maintanncegp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintancegp')),
            ],
        ),
        migrations.CreateModel(
            name='activeMaintance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enable', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintanance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintanance')),
                ('maintanncegp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintancegp')),
            ],
        ),
    ]
