# Generated by Django 4.0.6 on 2022-08-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0008_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintanance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('freq_in_loc', models.IntegerField(blank=True, null=True)),
                ('item_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemclass')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
            ],
        ),
    ]
