# Generated by Django 4.0.6 on 2022-08-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintanance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanance',
            name='requires',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
