# Generated by Django 4.0.6 on 2022-08-31 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_created_at_item_updated_at'),
        ('maintanance', '0004_activemaintance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='toDoMaintance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('maintanance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintanance')),
                ('maintanncegp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintancegp')),
            ],
        ),
        migrations.CreateModel(
            name='doneMaintance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('maintanance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintanance')),
                ('maintanncegp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintanance.maintancegp')),
            ],
        ),
    ]
