# Generated by Django 4.0.6 on 2022-09-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilityParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('topic', models.CharField(choices=[('Type', 'Other'), ('Physical fields', 'Physical'), ('Condition fields', 'Condition'), ('Fields specific to cold chain equipment', 'Cold'), ('Electrical fields', 'Electrical'), ('Financial fields', 'Financial'), ('Different codes', 'Different'), ('PQS/PIS fields', 'Pqs'), ('Dry store fields', 'Dry'), ('Other additional and optional fields', 'Add')], max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('fieldid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramfieldid', to='related.field')),
            ],
        ),
        migrations.CreateModel(
            name='relatedFacility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('topic', models.CharField(choices=[('Facility general information', 'Gen'), ('Information about services provided', 'Ser'), ('Facility physical conditions', 'Phy'), ('Human resource information', 'Hr'), ('Other optional fields', 'Other'), ('Other', 'Other1')], default='Facility general information', max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='relatedItemType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_field', to='related.field')),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_itemtype', to='items.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Itemvalidation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('digits', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('float', models.BooleanField(default=False)),
                ('floating', models.IntegerField(default=0)),
                ('fieldid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemvalfieldid', to='related.field')),
            ],
        ),
        migrations.CreateModel(
            name='itemParamDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('paramid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemparamid', to='related.itemparam')),
            ],
        ),
        migrations.CreateModel(
            name='Facilityvalidation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('digits', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('float', models.BooleanField(default=False)),
                ('floating', models.IntegerField(default=0)),
                ('fieldid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facvalfieldid', to='related.relatedfacility')),
            ],
        ),
        migrations.CreateModel(
            name='facilityParamDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('paramid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facparamid', to='related.facilityparam')),
            ],
        ),
        migrations.AddField(
            model_name='facilityparam',
            name='fieldid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facfieldid', to='related.relatedfacility'),
        ),
    ]
