# Generated by Django 4.0.6 on 2022-08-14 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemtypelevel_active'),
        ('related', '0002_relatedfacility_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('topic', models.CharField(choices=[('Type', 'Other'), ('Physical fields', 'Physical'), ('Condition fields', 'Condition'), ('Fields specific to cold chain equipment', 'Cold'), ('Electrical fields', 'Electrical'), ('Financial fields', 'Financial'), ('Different codes', 'Different'), ('PQS/PIS fields', 'Pqs'), ('Dry store fields', 'Dry'), ('Other additional and optional fields', 'Add')], max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='relatedfacility',
            name='topic',
            field=models.CharField(choices=[('Facility genera information', 'Gen'), ('Information about services provided', 'Ser'), ('Facility physical conditions', 'Phy'), ('Human resource information', 'Hr'), ('Other optional fields', 'Other'), ('Other', 'Other1')], default='Facility genera information', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='relatedItemType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related.field')),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtype')),
            ],
        ),
    ]
