# Generated by Django 4.0.6 on 2022-08-15 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0003_field_relatedfacility_topic_relateditemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilityParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('fieldid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related.relatedfacility')),
            ],
        ),
        migrations.CreateModel(
            name='itemParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('fieldid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related.field')),
            ],
        ),
        migrations.CreateModel(
            name='itemParamDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('paramid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related.itemparam')),
            ],
        ),
        migrations.CreateModel(
            name='facilityParamDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('paramid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related.facilityparam')),
            ],
        ),
    ]
