# Generated by Django 4.0.6 on 2022-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0004_facilityparam_itemparam_itemparamdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfacility',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='relatedfacility',
            name='topic',
            field=models.CharField(choices=[('Facility general information', 'Gen'), ('Information about services provided', 'Ser'), ('Facility physical conditions', 'Phy'), ('Human resource information', 'Hr'), ('Other optional fields', 'Other'), ('Other', 'Other1')], default='Facility general information', max_length=50, null=True),
        ),
    ]
