# Generated by Django 4.0.6 on 2022-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0006_relatedfacility_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
